### ISSUE TITLE
Multiple b0, personalization topup and T1 registration

### ISSUE THREAD

**Issue by mattvan83** [scilus/tractoflow#12]
Hello,

Thanks for this nice pipeline. I have some questions firstly regarding the use of multiple b0 in the pipeline and secondly about the personalization of both topup and T1 registration.

1) I used some data from Penthera3T in order to assess the pipeline, where 7 b0 were present in the dwi.nii.gz file. How does the pipeline deal with these several b0? Is an average of these 7 b0 computed at the beginning of the pipeline? If this is the case, are the 7 b0 realigned before computing the mean?

2) In my dataset I have only 1 b0 in the dwi.nii.gz file. In order to correct distorsions I have separately a set of 9 b0 in both AP and PA directions (computing mean from them to avoid noise of a unique b0 in the dwi.nii.gz). Then, I use both of them to estimate deformation field based on the mean b0 in AP and PA, then apply the distorsion correction on the dwi.nii.gz (having registered first the 9 b0 AP onto the unique b0 in the dwi.nii.gz file). How could I introduce this specific use of topup in the pipeline?

3) To register b0 onto T1, I use several registration from b0 to T2*, then to T2 and finally to T1. How could I introduce this specific registration in the pipeline?

Thanks for your time and advice.

Best,
Matthieu

**Comment by GuillaumeTh** [comment]
You can modify in your repository fork the steps but in our experience, the registration between the b0, fa and T1 is good.

**Comment by mattvan83** [comment]
Thanks for advice.

Modification of code in personal repository fork has to be based on nexflow code then?

**Comment by GuillaumeTh** [comment]
Yes your modifications must be in your own fork. 
I will close the issue due to a non direct link with tractoflow. If you have any questions you can open a new topic here https://neurostars.org/tags/tractoflow
