### ISSUE TITLE
Adding Gibb's Ringing correction

### ISSUE THREAD

**Issue by GuidoGuberman** [scilus/tractoflow#13]
Hi Guillaume Arnaud and JC,

Would it be possible to add a correction for Gibb's Ringing to the pipeline?

Thanks!

**Comment by GuillaumeTh** [comment]
Hi @GuidoGuberman, yes I added this feature in the feature list.

**Comment by GuidoGuberman** [comment]
Hi @GuillaumeTh, thank you!

**Comment by GuillaumeTh** [comment]
I close this issue. Duplicated with issue #17
