### ISSUE TITLE
Streamline analysis and connectivity

### ISSUE THREAD

**Issue by mattvan83** [scilus/tractoflow#14]
Hi,

Once the TractoFlow pipeline is finished, i.e. tracking is finished, one has a .trk file of whole brain streamline. But which way could you recommend us to continue with:

1) Visualization of tractography superposed onto anatomical image?
2) Streamline analysis and connectivity? (tools, methods available, ...)

**Comment by mattvan83** [comment]
Hi @GuillaumeTh , @jchoude ,

Could you give me details about my precedent question?

Many thanks for your time !

**Comment by GuillaumeTh** [comment]
@mattvan83 I don't have a general answer. It depends what you want to do with your diffusion data.

**Comment by mattvan83** [comment]
@GuillaumeTh, I would like first to identify regions that are structurally connected (through streamlines I guess), then apply connectivity analysis.

**Comment by GuillaumeTh** [comment]
@mattvan83 You can filter your tractogram using Region of Interest to check if two regions are connected. Then you can check a metrics value along this connection.

**Comment by mattvan83** [comment]
Thanks @GuillaumeTh !
What do you use to filter tractogram and check metrics value (FA, MD, ...) along connections?

**Comment by GuillaumeTh** [comment]
Hi @mattvan83, I will close this issue because of a non direct link with TractoFlow. If you have any questions you can open a new topic here https://neurostars.org/tags/tractoflow
