### ISSUE TITLE
Feature list for next releases

### ISSUE THREAD

**Issue by GuillaumeTh** [scilus/tractoflow#17]
Done

- [x] BIDS support
- [x] Auto binding of external drive
- [x] -Multiple seeds given for the tracking step
- [x] -Support local Tracking algorithm
- [x] -Gibbs correction

Feature list:

- [ ] -Add workdir in output_dir
- [ ] -Check version of nextflow
- [ ] -Add warning if some params are not good for replicability/reproducibility
- [ ] -Mutli-shell Multi-tissue fODF
- [ ] -Implement better registration step (https://www.biorxiv.org/content/10.1101/864108v2.full.pdf)
- [ ] -Add FSL bet for T1 (option)

**Comment by arnaudbore** [comment]
New feature:

- [x] Automatic shell detection
