### ISSUE TITLE
Change size of peaks nii.gz file

### ISSUE THREAD

**Issue by smeisler** [scilus/tractoflow#22]
Hello,

I would like to use TractSeg to postprocess my peaks.nii files. However, the program expects only 3 peaks, so the .nii should be [x,y,z,9], as this is the standard from MrTrix. However, the peaks.nii file from Tractoflor contains 5 peaks, leading to a [x,y,z,15] peaks.nii file. Is there a parameter I can set within Tractoflow to only produce 3 peaks, or alternatively a way to extract the 3 biggest peaks from nii?

Thanks,
Steven

**Comment by GuillaumeTh** [comment]
Hi smeisler,

We don't have alternative directly in TractoFlow to extract the 3 biggest peaks. However you can take the 9 first coefficients in the peaks.nii.gz file using mrconvert for example.

Best,

Guillaume

**Comment by GuillaumeTh** [comment]
I close this issue. If you have any other questions/problems, you can use https://neurostars.org/tags/tractoflow
