### ISSUE TITLE
T1 Alignment Recommended?

### ISSUE THREAD

**Issue by smeisler** [scilus/tractoflow#25]
Hi Tractoflow team,

Quick question: Should T1 files be ACPC aligned (or subject to any other alignment) before being put into Tractoflow? Also, should the x-gradient in the bvecs be flipped for data coming from Siemens scanners (this is recommended for other softwares like AFQ). Congrats on the _NeuroImage_ publication!

Thanks,
Steven

**Comment by GuillaumeTh** [comment]
Hi Steven,

T1 files can be in any space. The registration step will register the T1 on the DWI during the processing.

For the flipping, normally raw data in with any strides (except axis swapping) are supported on TractoFlow. However, following how your data was extracted from your Dicom, a flip must be mandatory. If you want, you can test on only one subject of your database and check if your data is flipped or not. I suggest you to deactivate: eddy and topup and set the number of seeds to 1 per voxels (just for testing your dataset). 

FYI, we will release a new version of TractoFlow in few days.

Thanks and good processing !

Guillaume
