### ISSUE TITLE
Seeding Masks Failing

### ISSUE THREAD

**Issue by smeisler** [scilus/tractoflow#26]
Hi Tractoflow team,

I am encountering an error when running Tractoflow with default parameters (besides turning Eddy correction off). I am running version 2.1.0 on a Linux HPC. Everything proceeds fine until reaching the Seeding Masks phase. I notice in the Slurm out file, that for every subject that enters the task, there are reports of 4 failures. For example, below are the last three lines from the process I am running currently:

[cd/a2a9fd] process > Segment_Tissues    [100%] 4 of 4
[03/949a05] process > PFT_Maps           [100%] 4 of 4
[e4/d0873c] process > Seeding_Mask       [100%] 16 of 16, failed: 16

I had a similar error in a previous version of Tractoflow when running Eddy without specifying a singularity config file, but the changelog suggests config files are not needed anymore. Please let me know if you would need any more information to diagnose the issue.

Thanks,
Steven

**Comment by GuillaumeTh** [comment]
Hi Steven,

Sorry to hear that. We have some issues with the new release. We are currently working to fix all the issues and we will repackage everything. I will probably remove 2.1.0 release for now.

Could you give me the output of the following command please:

`cat work/e4/d0873c*/.command.log`

Guillaume

**Comment by smeisler** [comment]
nxf-scratch-dir node007:/tmp/nxf.K7Vbld7Uk0
/net/oms.ib.cluster/om4/group/gablab/data/reader/derivatives/dprep_tractoflow_test/work/e4/d0873c5c88a031b4b1f8c22cd89369/.command.sh: line 5: scil_mask_math.py: command not found

**Comment by GuillaumeTh** [comment]
Hi Steven,

I think you have a mismatch in the versions. I think that you use the code of TractoFlow of version 2.0.1 but with the singularity 2.1.0.

I propose you to wait few days. I currently repackaging the release to fix a bug. I can ping you here when it will be ok to use it. 

Best,

Guillaume

**Comment by smeisler** [comment]
Ah, that is probably the issue. Sounds good, I will wait for the bugs to be fixed, thanks!

**Comment by smeisler** [comment]
Tried the new release, looks like it works thanks!

**Comment by GuillaumeTh** [comment]
You were faster than me to annonce you the release ! :smile:
