### ISSUE TITLE
Run Topup, but not Eddy; How to deal with different acquisition parameters.

### ISSUE THREAD

**Issue by smeisler** [scilus/tractoflow#29]
Hi Tractoflow team,

I do QC with DTIPrep, which does Eddy + motion correction as well as automated volume removal, before using Tractoflow. Therefore, I do not need to do Eddy and motion again so I set --run_eddy false. However, DTIPrep does not do Topup, and some of my datasets have reverse b0 images. In the Slurm outfile, it looks like Eddy and Topup are one process (called Eddy). Is it possible to only run topup, or should I run topup before using Tractoflow?

Similarly, in this dataset there are some subjects who have reverse-encoded b0 and some who do not. What would be your suggested way of dealing with this? My main concern is that ideally all subjects would be considered in the mean FRF.

Thank you,
Steven

**Comment by GuillaumeTh** [comment]
Hi Steven,

Could you move your question to Neurostar: https://neurostars.org/tags/tractoflow .

We prefer keep the issue tab of Github for code issues/requests.

Best

Guillaume

**Comment by smeisler** [comment]
[Done](https://neurostars.org/t/run-topup-but-not-eddy-how-to-deal-with-different-acquisition-parameters/7681)
