### ISSUE TITLE
Remote Resource not found

### ISSUE THREAD

**Issue by FL33TW00D** [scilus/tractoflow#31]
Hi Tractoflow team,
I am attempting to run your pipeline on some OASIS DWI data on a CentOS HPC running SLURM.

I have successfully built a tractoflow image, and the HPC team has added singularity 3.6.0 and Nextflow 20.04.1 to the modules.

Upon running, I recieve the following error:

N E X T F L O W ~ version 20.04.1
Pulling nextflow-io/tractoflow …
Remote resource not found: https://api.github.com/repos/nextflow-io/tractoflow/contents/main.nf

I have downloaded the main.nf and nextflow.config from your repo, but to no avail.

Any ideas?

**Comment by FL33TW00D** [comment]
Fixed this.

For Future readers, trying to run on SLURM HPC:
1.  wget https://github.com/scilus/tractoflow/releases/download/2.1.1/tractoflow-2.1.1.zip && unzip tractoflow-2.1.1.zip
2.  wget http://scil.dinf.usherbrooke.ca/containers_list/tractoflow_2.1.1_650f776_2020-07-15.img
3. nextflow run tractoflow-2.1.1/main.nf --bids YOUR_FOLDER --dti_shells "DTI_SHELLS" --fodf_shells "FODF_SHELLS" -with-singularity tractoflow_2.1.1_650f776_2020-07-15.img -resume

**Comment by GuillaumeTh** [comment]
Hi @FL33TW00D ,

We already have this information here: https://tractoflow-documentation.readthedocs.io/en/latest/installation/install.html

Do you have any advices to improve this documentation ?

Best

Guillaume

**Comment by FL33TW00D** [comment]
@GuillaumeTh 
Hi Guillaume,
It was a combination of silly mistakes from me and a few tiny things to change in the documentation.
![image](https://user-images.githubusercontent.com/45471420/89537493-54526e80-d7f1-11ea-9057-8ab6626064ea.png)
In the image above it specifies tractoflow instead of tractoflow-(version number). I should have spotted this silly mistake on my part.

**Comment by GuillaumeTh** [comment]
Oh yes ! Good catch ! Thank you very much for your feed back !
