### ISSUE TITLE
Eddy Process error exit status (134)

### ISSUE THREAD

**Issue by FL33TW00D** [scilus/tractoflow#33]
Hi Tractoflow team,
Do you possibly have a reference for the error codes that are produced by Tractoflow?

I have encountered the following error: `Eddy (sub-OAS30125_ses-d0201)` terminated with an error exit status (134) -- Execution is retried (3)

**Comment by arnaudbore** [comment]
Can you post this issue in Neurostars please, it will be easier for future users to learn from your problem.
Thank you in advance.

**Comment by FL33TW00D** [comment]
@arnaudbore Apologies I will do.
