### ISSUE TITLE
feature request: gradunwarp

### ISSUE THREAD

**Issue by bpinsard** [scilus/tractoflow#50]
Are there any plans to include https://github.com/Washington-University/gradunwarp to the pipeline? 
It would help using the pipeline on data acquired with the HCP acquisition scheme.
Thanks!

**Comment by GuillaumeTh** [comment]
Hi @bpinsard,

It is not planned to add this in tractoflow. This script is very specific and not well adapted for tractoflow.

Best

Guillaume
