### ISSUE TITLE
Tractoflow pipeline error “Read Bids”

### ISSUE THREAD

**Issue by Gar1-icm** [scilus/tractoflow#52]
Hello,
I am trying to launch the tractoflow pipeline on a example dataset (https://openneuro.org/datasets/ds003047/versions/1.0.0 1) on a linux system.
When I launch the pipeline I get an error with the “Read_BIDS” :
/Tractoflow [512] > ./nextflow run tractoflow/main.nf --bids /home/giacomo.garone/Tractoflow/DATA/ds003047-download --dti_shells “0 1000” --fodf_shells “0 1000” -with-singularity /home/giacomo.garone/Tractoflow/tractoflow_2.2.1_b9a527_2021-04-13.sif -resume
N E X T F L O W ~ version 19.04.0
Launching tractoflow/main.nf [pensive_jones] - revision: f66d0cdd95
TractoFlow pipeline
Start time: Fri Jul 23 17:22:05 CEST 2021
Input BIDS: /home/giacomo.garone/Tractoflow/DATA/ds003047-download
Clean_bids: false
executor > local (8)
[03/751dc8] process > Read_BIDS [100%] 4 of 4, failed: 4 ✘
[e8/6d6713] process > README [100%] 4 of 4, failed: 4
Pipeline completed at: Fri Jul 23 17:22:13 CEST 2021
Execution status: failed
Execution duration: 7.7s
[21/c99155] NOTE: Process Read_BIDS (Read_BIDS) terminated with an error exit status (255) – Execution is retried (1)
[92/cab5cc] NOTE: Process README (README) terminated with an error exit status (255) – Execution is retried (1)
[b5/61dbb3] NOTE: Process Read_BIDS (Read_BIDS) terminated with an error exit status (255) – Execution is retried (2)
[1b/1b259d] NOTE: Process README (README) terminated with an error exit status (255) – Execution is retried (2)
[46/13a5dc] NOTE: Process Read_BIDS (Read_BIDS) terminated with an error exit status (255) – Execution is retried (3)
[22/ab40bf] NOTE: Process README (README) terminated with an error exit status (255) – Execution is retried (3)
WARN: Killing pending tasks (1)
ERROR ~ Error executing process > ‘Read_BIDS (Read_BIDS)’
Caused by:
Process Read_BIDS (Read_BIDS) terminated with an error exit status (255)
Command executed:
scil_validate_bids.py ds003047-download tractoflow_bids_struct.json --readout 0.062
Command exit status:
255
Command output:
(empty)
Command error:
FATAL: container creation failed: mount /proc/self/fd/10->/usr/local/var/singularity/mnt/session/rootfs error: can’t mount image /proc/self/fd/10: failed to mount squashfs filesystem: invalid argument
Work dir:
/home/giacomo.garone/Tractoflow/work/03/751dc885216a34b64c8d291552c3a4
Tip: you can replicate the issue by changing to the process work dir and entering the command bash .command.run
– Check ‘.nextflow.log’ file for details

Can someone help me ?
Thank you very much in advance for your help !
Best
Giacomo

**Comment by arnaudbore** [comment]
Hi @Gar1-icm ,

Sorry for the long delay, we do not use github issues to help people.
Please use https://neurostars.org/ instead if you have any issues.
