### ISSUE TITLE
Multiple reverse b0 not supported

### ISSUE THREAD

**Issue by frheault** [scilus/tractoflow#6]
While processing a dataset I realize that rev_b0 can contain multiple volume (100x100x68x6) and it seems the scripts scil_prepare_topup_command.py does not support it. Well in fact nothing crash and topup takes a lot more time than usual without a visible improvement of results.

If this is the expected behavior, documentation should be adjusted in consequence. 
If not, the script scil_prepare_topup_command.py should crash

**Comment by GuillaumeTh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TractoFlow: Fix issue #6](https://trello.com/c/F4k10bcV/131-tractoflow-fix-issue-6)
