### ISSUE TITLE
^Minor¸Topup mean rev_b0 error when 3D data

### ISSUE THREAD

**Issue by karanphil** [scilus/tractoflow#62]
There is a small issue with the command `scil_image_math.py mean $rev_b0 $rev_b0 --data_type float32 -f` in the topup process. If the rev_b0 is in 3D (which happens to be my case quite often), the scilpy script returns an error and tractoflow continues with the unchanged $rev_b0. This is only a minor issue, since all it implies is that the dtype of $rev_b0 remains unchanged (so probably int16 instead of float32). This is a small detail that only affects the Ants command right after, but I suggest to add a `scil_image_math.py convert` command to be sure that the processes are always with float32.

**Comment by arnaudbore** [comment]
@karanphil does not seem to be still in the master. Do you still have this issue or can we close it ?
