### ISSUE TITLE
Tractoflow does not support multi shell multi tissue CSD (MSMT-CSD)

### ISSUE THREAD

**Issue by PaulBautin** [scilus/tractoflow#66]
Tractoflow pipeline does not support multi-shell multi-tissue CSD (MSMT-CSD). Only single shell single tissue (SSST-CSD) has been implemented even though `scil_compute_msmt_fodf.py` and `scil_compute_msmt_frf.py` exist.

A solution is to add an option in Tractoflow to use either the single shell fODF* or MSMT version.

An alternative solution would be to implement a new Nextflow pipeline for computing MSMT-fODF from Tractoflow ouptuts (similar to freewater_flow or NODDI_flow). However, the new pipeline would only improve fODF metrics (ex. for tractometry) but not the tractography! 

*Multi shell CSD is actually already supported in Tractoflow. However, Tractoflow only estimates (user can also manually enter) a single FRF for all shells thus it can apply SSST-CSD.

**Comment by arnaudbore** [comment]
#83
