### ISSUE TITLE
Updated Docker image?

### ISSUE THREAD

**Issue by Shade-** [scilus/tractoflow#70]
Hello, just a friendly reminder asking you to update the Docker image to the latest version (2.3.0). Thanks for this awesome piece of software!

**Comment by arnaudbore** [comment]
Hi @Shade- ,
Actually we are currently working on the new version 2.4.0. Should be out in a couple of days/weeks.
New really nice features coming up !

**Comment by arnaudbore** [comment]
@Shade- New docker + documentation has been released end of 2022.
We'll have a new release soon fixing a small issue with magnitude/phase MB DWI acquisitions.
