### ISSUE TITLE
Nexflow error

### ISSUE THREAD

**Issue by yizhwan** [scilus/tractoflow#78]
HI, I get an error running tractoflow on UBuntu 22.04 Jammy after installing Netflow successfully:

sudo nextflow run tractoflow -r 2.4.2
gives:

Nextflow DSL1 is no longer supported — Update your script to DSL2, or use Nextflow 22.10.x or earlier

Any ideas how to solve this issue?

**Comment by arnaudbore** [comment]
Hi @yizhwan,

Check you nextflow version but like the error message says you should be using Nextflow 22.10.x or earlier.

Don't hesitate to reopen an issue if you still have this issue.
