### ISSUE TITLE
problems lauching tractoflow on Ubuntu 22.04 Jammy

### ISSUE THREAD

**Issue by yizhwan** [scilus/tractoflow#79]
Hi, 

I have a Ubuntu 22.04 desktop system with 64GB of memory and i9 intel processor. I have have tried running via singularity with the following command via a bash shell script:

NXF_VER=22.10.4 nextflow run tractoflow -r 2.4.2 --input $wkdir/dwi_preproc -profile use_cuda ABS fully_reproducible --readout 0.0708501 --run_t1_denoising false --processes 4 --run_pft_tracking false -with-singularity $pathto/scilus_1.5.0.sif 

While some of the processes do run e.g. denoise dwi and prepare for topup. It will always stop running and generate the following error in the .nextflow.log file:

01:54:30.574 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 371; name: Eddy_Topup (S12); status: COMPLETED; exit: 255; error: -; workDir: $pathto/dwi_preproc/work/98/750822d4c3c955352fd33dc556cc96]

This error is repeated as it trys to rerun eddy_topup.

The same exit error 225 is also displayed in the terminal.

Could anyone help?

Thanks

Yizhou

**Comment by yizhwan** [comment]
I have fixed the above issue by removing previous log files for previous attempted runs of nextflow. However, after running the command I get the error:

WARN: Cannot read project manifest -- Cause: Remote resource not found: https://api.github.com/repos/nextflow-io/tractoflow/contents/nextflow.config?ref=2.4.2
Remote resource not found: https://api.github.com/repos/nextflow-io/tractoflow/contents/main.nf?ref=2.4.2

**Comment by yizhwan** [comment]
Furthermore, if there any way to turn off brain extraction and N4 bias correction for T1 if you have already performed these operations with another pipeline and give tractoflow the skull stripped T1 with a brain mask?

**Comment by arnaudbore** [comment]
Hi @yizhwan ,

I would need to know what's in this file: `$pathto/dwi_preproc/work/98/750822d4c3c955352fd33dc556cc96/.command.err` 

Profiles should be separated by commas like this [profiles](https://tractoflow-documentation.readthedocs.io/en/latest/pipeline/profiles.html#profiles)

Sadly so far, brain extraction and N4 bias correction can't be avoided. I will code this for the next release.

**Comment by yizhwan** [comment]
Hi, thanks for your quick response. The .command.err shows:

[[31mFATAL:  ^[[0m container creation failed: mount /proc/self/fd/3->/usr/local/var/singularity/mnt/session/rootfs error: while mounting image /proc/self/fd/3: failed to find loop device: could not attach image file to loop device: no loop devices available

**Comment by yizhwan** [comment]
I am now able to get tractoflow working via Docker on my system with the following command via bash shell script:

NXF_VER=22.10.4 nextflow run tractoflow -r 2.4.2 --input $wkdir/data/derivatives/dwi_preproc -profile use_cuda,ABS,fully_reproducible --readout 0.0708501 --run_t1_denoising false --processes 4 --run_pft_tracking false -with-docker scilus/scilus:1.5.0 -resume

My questions are:

1. Should I just continue to do this, instead of SIngularity or is there a fix for my previous singularity issue?
2. TF works fine until it tries to run eddy_cuda. The error log says: 

WARNING:root:eddy_cuda not found. If executing locally, please install the command from the FSL library and make sure it is available in your path.
WARNING:root:Least-square resampling disabled since number of directions in both phase directions differ.
eddy.sh: 1: eddy_cuda: not found

Now this is odd because I am running TF in a conda environment where I have eddy_cuda installed and I have tested eddy_cuda- it runs fine. 

Furthermore, $FSLDIR is in my .bashrc and my $FSLDIR/bin shows that eddy_cuda points to the right path:

eddy_cuda -> /usr/local/KUL_apps/eddy_cuda/eddy_cuda11.2

Could this be because TF is looking for a different version of eddy_cuda?

**Comment by arnaudbore** [comment]
Hi @yizhwan ,

> I am now able to get tractoflow working via Docker on my system with the following command via bash shell script:
> 
Great news

> NXF_VER=22.10.4 nextflow run tractoflow -r 2.4.2 --input $wkdir/data/derivatives/dwi_preproc -profile use_cuda,ABS,fully_reproducible --readout 0.0708501 --run_t1_denoising false --processes 4 --run_pft_tracking false -with-docker scilus/scilus:1.5.0 -resume
> 
> My questions are:
> 
> 1. Should I just continue to do this, instead of SIngularity or is there a fix for my previous singularity issue?

I would say yes if you get stuck with singularity, go with docker. It's not a tractoflow issue but more a singularity one. 
Which version of singularity are you using ? Can you try to delete singularity and install apptainer ? 

> 2. TF works fine until it tries to run eddy_cuda. The error log says:
> 
> WARNING:root:eddy_cuda not found. If executing locally, please install the command from the FSL library and make sure it is available in your path. WARNING:root:Least-square resampling disabled since number of directions in both phase directions differ. eddy.sh: 1: eddy_cuda: not found
> 
> Now this is odd because I am running TF in a conda environment where I have eddy_cuda installed and I have tested eddy_cuda- it runs fine.
> 

Just add --eddy_cmd eddy_cuda10.2

> Furthermore, $FSLDIR is in my .bashrc and my $FSLDIR/bin shows that eddy_cuda points to the right path:
> 
> eddy_cuda -> /usr/local/KUL_apps/eddy_cuda/eddy_cuda11.2
> 
> Could this be because TF is looking for a different version of eddy_cuda?

No, I just need to add a symlink eddy_cuda -> eddy_cuda10.2 in the container.

**Comment by arnaudbore** [comment]
Dear @yizhwan,
Do you still have any issue with tractoflow ? Otherwise I will close this issue.

**Comment by yizhwan** [comment]
Many thanks, I can confirm Tractoflow is working now in it's default method. I did open another request regarding customising the run though.
